services:
  portfolio:
    image: portfolio-website
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: ["node", "backend/public.js"]