services:
  # Frontend service
  portfolio:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: ["node", "backend/public.js"]  # Start de public server